import { defineConfig } from 'vite';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { existsSync, readdirSync } from 'node:fs';

// Discover blog pages (generated by scripts/build-blog.mjs) so adding a post
// never requires editing this file. Picks up blog/index.html and every
// blog/<slug>/index.html.
function blogInputs() {
  const inputs = {};
  const blogDir = resolve(__dirname, 'blog');
  if (!existsSync(blogDir)) return inputs;
  if (existsSync(resolve(blogDir, 'index.html'))) {
    inputs.blog = resolve(blogDir, 'index.html');
  }
  for (const entry of readdirSync(blogDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const page = resolve(blogDir, entry.name, 'index.html');
    if (existsSync(page)) inputs[`blog-${entry.name}`] = page;
  }
  return inputs;
}

export default defineConfig({
  plugins: [
    {
      name: 'malibu-release-api',
      configureServer(server) {
        server.middlewares.use(async (req, res, next) => {
          const path = req.url?.split('?')[0];
          if (path === '/api/host-compatibility') {
            const { default: handler } = await import(
              `${pathToFileURL(resolve(__dirname, 'api/host-compatibility.js')).href}?dev=${Date.now()}`
            );
            await handler(req, res);
            return;
          }
          if (path !== '/api/malibu-release') {
            next();
            return;
          }
          if (req.method !== 'GET') {
            res.statusCode = 405;
            res.setHeader('Allow', 'GET');
            res.setHeader('Content-Type', 'application/json; charset=utf-8');
            res.end(JSON.stringify({ error: 'method_not_allowed' }));
            return;
          }
          try {
            const { resolveLatestMalibuRelease } = await import(
              pathToFileURL(resolve(__dirname, 'j/latest-release.mjs')).href
            );
            const { isAcceptedMalibuDownload } = await import(
              pathToFileURL(resolve(__dirname, 'j/release.mjs')).href
            );
            const release = await resolveLatestMalibuRelease();
            if (!isAcceptedMalibuDownload(release)) {
              throw new Error('resolved release failed public download checks');
            }
            res.statusCode = 200;
            res.setHeader('Content-Type', 'application/json; charset=utf-8');
            res.setHeader('Cache-Control', 'no-store');
            res.end(JSON.stringify({
              tag: release.tag,
              url: release.url,
              sha256: release.sha256,
            }));
          } catch {
            res.statusCode = 502;
            res.setHeader('Content-Type', 'application/json; charset=utf-8');
            res.setHeader('Cache-Control', 'no-store');
            res.end(JSON.stringify({ error: 'release_unavailable' }));
          }
        });
      },
    },
  ],
  server: {
    proxy: {
      '/auth': {
        target: 'https://api.streamvc.live',
        changeOrigin: true,
      },
      '/account': {
        target: 'https://api.streamvc.live',
        changeOrigin: true,
      },
      '/api/mp': {
        target: 'https://api.streamvc.live',
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/api\/mp/, ''),
      },
      '/v1/stats': {
        target: 'https://api.malibu.tech',
        changeOrigin: true,
      },
      '/v1/rate-card': {
        target: 'https://coordinator.streamvc.live',
        changeOrigin: true,
      },
      '/v1/pool/check': {
        target: 'https://coordinator.streamvc.live',
        changeOrigin: true,
      },
      '^/providers/[^/]+/earnings$': {
        target: 'https://coordinator.streamvc.live',
        changeOrigin: true,
      },
    },
  },
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        console: resolve(__dirname, 'console/index.html'),
        consoleDashboard: resolve(__dirname, 'console/dashboard/index.html'),
        consoleKeys: resolve(__dirname, 'console/keys/index.html'),
        consoleSettings: resolve(__dirname, 'console/settings/index.html'),
        consoleAgentDocs: resolve(__dirname, 'console/agent-docs/index.html'),
        consoleTeam: resolve(__dirname, 'console/team/index.html'),
        consoleAuthCallback: resolve(__dirname, 'console/auth/callback.html'),
        widget: resolve(__dirname, 'widget/index.html'),
        host: resolve(__dirname, 'host/index.html'),
        hostTroubleshoot: resolve(__dirname, 'host/troubleshoot/index.html'),
        join: resolve(__dirname, 'j/index.html'),
        network: resolve(__dirname, 'network/index.html'),
        sellerPortal: resolve(__dirname, 'seller-portal/index.html'),
        privacy: resolve(__dirname, 'privacy/index.html'),
        terms: resolve(__dirname, 'terms/index.html'),
        ...blogInputs(),
      },
    },
  },
});
