import { defineConfig } from 'vite';
import { resolve } from 'node:path';
import { existsSync, readdirSync } from 'node:fs';

// Discover blog pages (generated by scripts/build-blog.mjs) so adding a post
// never requires editing this file. Picks up blog/index.html and every
// blog/<slug>/index.html.
function blogInputs() {
  const inputs = {};
  const blogDir = resolve(__dirname, 'blog');
  if (existsSync(resolve(blogDir, 'index.html'))) {
    inputs.blog = resolve(blogDir, 'index.html');
  }
  for (const entry of readdirSync(blogDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const page = resolve(blogDir, entry.name, 'index.html');
    if (existsSync(page)) inputs[`blog-${entry.name}`] = page;
  }
  return inputs;
}

export default defineConfig({
  server: {
    proxy: {
      '/auth': {
        target: 'https://api.streamvc.live',
        changeOrigin: true,
      },
      '/account': {
        target: 'https://api.streamvc.live',
        changeOrigin: true,
      },
      '/api/mp': {
        target: 'https://api.streamvc.live',
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/api\/mp/, ''),
      },
      '/v1/stats': {
        target: 'https://stats.streamvc.live',
        changeOrigin: true,
      },
      '/v1/rate-card': {
        target: 'https://coordinator.streamvc.live',
        changeOrigin: true,
      },
      '/v1/pool/check': {
        target: 'https://coordinator.streamvc.live',
        changeOrigin: true,
      },
      '^/providers/[^/]+/earnings$': {
        target: 'https://coordinator.streamvc.live',
        changeOrigin: true,
      },
    },
  },
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        console: resolve(__dirname, 'console/index.html'),
        consoleDashboard: resolve(__dirname, 'console/dashboard/index.html'),
        consoleKeys: resolve(__dirname, 'console/keys/index.html'),
        consoleSettings: resolve(__dirname, 'console/settings/index.html'),
        consoleAgentDocs: resolve(__dirname, 'console/agent-docs/index.html'),
        consoleTeam: resolve(__dirname, 'console/team/index.html'),
        consoleAuthCallback: resolve(__dirname, 'console/auth/callback.html'),
        widget: resolve(__dirname, 'widget/index.html'),
        host: resolve(__dirname, 'host/index.html'),
        hostTroubleshoot: resolve(__dirname, 'host/troubleshoot/index.html'),
        network: resolve(__dirname, 'network/index.html'),
        sellerPortal: resolve(__dirname, 'seller-portal/index.html'),
        ...blogInputs(),
      },
    },
  },
});
