#!/usr/bin/env node
/**
 * Build the Malibu blog from Markdown sources.
 *
 * Source of truth:  blog/posts/<slug>.md   (frontmatter + Markdown body)
 * Generated:        blog/<slug>/index.html (one per post, a Vite input via glob)
 *                   blog/index.html         (post listing)
 *                   public/sitemap.xml      (served at /sitemap.xml)
 *                   public/blog/feed.xml    (served at /blog/feed.xml)
 *
 * Adding a post = add one Markdown file and run `npm run blog:build`.
 * Never edit the generated files or vite.config.js by hand.
 *
 * SECURITY: post bodies may be authored by an unattended agent, so all
 * untrusted values are treated as hostile: bodies are sanitized against an
 * allowlist, JSON-LD is escaped for <script> context, and every XML sink is
 * entity-escaped. One malformed post is skipped, never fatal to the build.
 */
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';
import sanitizeHtml from 'sanitize-html';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const postsDir = join(root, 'blog', 'posts');
const blogDir = join(root, 'blog');
const publicDir = join(root, 'public');

const SITE = 'https://malibu.tech';
const DEFAULT_AUTHOR = 'The Malibu team';
const DEFAULT_HERO = '/images/brand/blog-hero-macbook-sunset-mesh.jpg';
const RESERVED_SLUGS = new Set(['posts', 'index', 'feed']);
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const BANNER_MARK = 'GENERATED by scripts/build-blog.mjs';
const BANNER = (slug) =>
  `<!-- ${BANNER_MARK} from blog/posts/${slug}.md — do not edit directly. -->`;

// ---------------------------------------------------------------------------
// Escaping — one helper per output context. Never mix them up.
// ---------------------------------------------------------------------------

const escAttr = (s = '') =>
  String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

const escText = (s = '') =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// XML text/attribute content — escape the full entity set.
const escXml = (s = '') =>
  String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');

// JSON embedded in <script type="application/ld+json"> — neutralize the byte
// sequences that could close the tag or break out of the block.
const jsonForScript = (obj) =>
  JSON.stringify(obj, null, 2)
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e')
    .replace(/&/g, '\\u0026')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');

const slugify = (s = '') =>
  String(s)
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/[\s_]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');

function formatDate(str) {
  const d = new Date(str);
  if (Number.isNaN(d.getTime())) return '';
  return `${MONTHS[d.getUTCMonth()]} ${d.getUTCDate()}, ${d.getUTCFullYear()}`;
}

// ---------------------------------------------------------------------------
// Markdown → sanitized HTML, with heading anchors + a table of contents.
// ---------------------------------------------------------------------------

marked.setOptions({ gfm: true, breaks: false });
marked.use({
  renderer: {
    heading({ tokens, depth, text }) {
      const inner = this.parser.parseInline(tokens);
      const id = slugify(text);
      return `<h${depth}${id ? ` id="${escAttr(id)}"` : ''}>${inner}</h${depth}>\n`;
    },
  },
});

const SANITIZE = {
  allowedTags: [
    'p', 'a', 'ul', 'ol', 'li', 'strong', 'em', 'b', 'i', 'code', 'pre',
    'blockquote', 'hr', 'br', 'h2', 'h3', 'h4', 'img', 'span',
  ],
  allowedAttributes: {
    '*': ['id'],
    a: ['href', 'title', 'target', 'rel'],
    img: ['src', 'alt', 'title', 'width', 'height', 'loading'],
  },
  allowedSchemes: ['http', 'https', 'mailto'],
  allowedSchemesByTag: { img: ['http', 'https', 'data'] },
  transformTags: {
    // Add rel=noopener while MERGING (keep href/title); javascript: hrefs are
    // dropped by the scheme allowlist above.
    a: sanitizeHtml.simpleTransform('a', { rel: 'noopener' }, true),
  },
};

function renderBody(markdown) {
  const dirty = marked.parse(markdown);
  return sanitizeHtml(dirty, SANITIZE);
}

function tableOfContents(markdown) {
  const headings = marked
    .lexer(markdown)
    .filter((t) => t.type === 'heading' && t.depth === 2)
    .map((t) => ({ text: t.text, id: slugify(t.text) }))
    .filter((h) => h.id);
  return headings;
}

// ---------------------------------------------------------------------------
// Frontmatter — minimal, controlled format. Values are raw strings/booleans;
// list normalization happens per-field in loadPost so a bare `keywords: a, b`
// can never crash the build.
// ---------------------------------------------------------------------------

function parseFrontmatter(raw) {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!m) return { data: {}, body: raw };
  const data = {};
  for (const line of m[1].split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = line.indexOf(':');
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    let val = line.slice(idx + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    if (val === 'true' || val === 'false') data[key] = val === 'true';
    else data[key] = val;
  }
  return { data, body: m[2] };
}

function toList(val) {
  if (Array.isArray(val)) return val;
  if (val == null || val === '') return [];
  return String(val)
    .replace(/^\[|\]$/g, '')
    .split(',')
    .map((s) => s.trim().replace(/^["']|["']$/g, ''))
    .filter(Boolean);
}

// Optional structured-data fields carry a one-line JSON value. Malformed JSON is
// warned + ignored (the FAQ/HowTo is simply omitted) rather than dropping the post.
function parseJsonField(raw, label) {
  if (!raw) return null;
  try {
    return JSON.parse(raw);
  } catch (err) {
    console.warn(`build-blog: ignoring malformed "${label}" JSON — ${err.message}`);
    return null;
  }
}

// Require actual strings — never String()-coerce, or `{"a":42}` ships "42" and
// `{"q":{...}}` ships "[object Object]" as visible + indexed FAQ content.
const str = (v) => (typeof v === 'string' ? v.trim() : '');

function normalizeFaq(v) {
  if (!Array.isArray(v)) return [];
  return v
    .map((it) => ({ q: str(it?.q), a: str(it?.a) }))
    .filter((it) => it.q && it.a);
}

function normalizeHowto(v) {
  if (!v) return null;
  const rawSteps = Array.isArray(v) ? v : Array.isArray(v.steps) ? v.steps : [];
  const steps = rawSteps
    .map((s) => (typeof s === 'string' ? { name: '', text: str(s) } : { name: str(s?.name), text: str(s?.text) || str(s?.name) }))
    .filter((s) => s.text);
  if (!steps.length) return null;
  return {
    name: Array.isArray(v) ? '' : str(v.name),
    totalTime: Array.isArray(v) ? '' : str(v.totalTime),
    steps,
  };
}

function loadPosts() {
  if (!existsSync(postsDir)) return [];
  const posts = [];
  for (const file of readdirSync(postsDir)) {
    if (!file.endsWith('.md')) continue;
    try {
      const raw = readFileSync(join(postsDir, file), 'utf8');
      const { data, body } = parseFrontmatter(raw);
      const slug = slugify(data.slug || basename(file, '.md'));
      if (!slug) throw new Error('empty slug');
      if (RESERVED_SLUGS.has(slug)) throw new Error(`reserved slug "${slug}"`);
      if (!data.title || !data.date) throw new Error('missing required frontmatter (title, date)');
      if (Number.isNaN(new Date(data.date).getTime())) {
        throw new Error(`unparseable date "${data.date}"`);
      }
      // Fail SAFE on draft: any truthy-looking value keeps the post unpublished,
      // so a stray `draft: true # note` (string) never leaks live. Only an
      // explicit falsey value publishes.
      const draftVal = data.draft;
      const isDraft =
        draftVal === true ||
        (typeof draftVal === 'string' && /^\s*(true|yes|on|1|draft)\b/i.test(draftVal));
      if (isDraft) continue;

      const canonical = data.canonical || `${SITE}/blog/${slug}/`;
      const rawOgImage = data.ogImage || data.heroImage || DEFAULT_HERO;
      const ogImage = rawOgImage.startsWith('/') ? `${SITE}${rawOgImage}` : rawOgImage;
      const words = body.trim().split(/\s+/).filter(Boolean).length;

      // Warn when structured-data frontmatter is present but yields nothing
      // usable (e.g. a bare array of the wrong shape) — silent omission hides bugs.
      const faqRaw = parseJsonField(data.faq, 'faq');
      const faq = normalizeFaq(faqRaw);
      if (faqRaw && !faq.length) console.warn(`build-blog: ${file} — "faq" had no usable {q,a} pairs; omitting.`);
      const howtoRaw = parseJsonField(data.howto, 'howto');
      const howto = normalizeHowto(howtoRaw);
      if (howtoRaw && !howto) console.warn(`build-blog: ${file} — "howto" had no usable steps; omitting.`);

      posts.push({
        slug,
        title: data.title,
        headline: data.headline || data.title,
        category: data.category || 'Notes',
        author: data.author || DEFAULT_AUTHOR,
        date: data.date,
        dateModified: data.updated || data.date,
        dateDisplay: formatDate(data.date),
        readingTime: Math.max(1, Math.round(words / 200)),
        description: data.description || data.lede || '',
        ogTitle: data.ogTitle || data.title,
        ogDescription: data.ogDescription || data.description || data.lede || '',
        ogImage,
        isDefaultHero: ogImage.endsWith('blog-hero-macbook-sunset-mesh.jpg'),
        lede: data.lede || '',
        excerpt: data.excerpt || data.lede || data.description || '',
        heroImage: data.heroImage || '',
        heroAlt: data.heroAlt || '',
        keywords: toList(data.keywords),
        canonical,
        faq,
        howto,
        bodyHtml: renderBody(body.trim()),
        toc: tableOfContents(body.trim()),
      });
    } catch (err) {
      console.warn(`build-blog: skipping blog/posts/${file} — ${err.message}`);
    }
  }
  return posts.sort((a, b) => new Date(b.date) - new Date(a.date));
}

// ---------------------------------------------------------------------------
// Shared chrome
// ---------------------------------------------------------------------------

const HEAD_ASSETS = `  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Hanken+Grotesk:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet" />
  <link rel="icon" href="/favicon.png" type="image/png" sizes="512x512" />
  <link rel="icon" href="/favicon-32.png" type="image/png" sizes="32x32" />
  <link rel="alternate" type="application/rss+xml" title="Malibu · Blog" href="/blog/feed.xml" />
  <link rel="stylesheet" href="/src/styles.css" />`;

const nav = (menuId) => `<nav data-nav-pill aria-label="Primary navigation" style="position: fixed; top: 22px; left: 50%; transform: translateX(-50%); z-index: 100; display: flex; align-items: center; gap: 28px; height: 56px; padding: 0 10px 0 20px; background: #143A45; border-radius: 9999px; box-shadow: 0 18px 50px -22px rgba(20, 58, 69,0.55), 0 2px 6px rgba(20, 58, 69,0.18);">
  <a href="/" class="brand-lockup" style="padding-right: 10px; border-right: 1px solid rgba(250, 251, 255,0.12);">
    <span class="brand-mark-circle">
      <img src="/logo-mark.png" width="28" height="28" alt="" aria-hidden="true" />
    </span>
    <span class="brand-wordmark">Malibu<span class="brand-period brand-period--square" aria-hidden="true"></span></span>
  </a>
  <button type="button" data-nav-toggle aria-expanded="false" aria-controls="${menuId}" aria-label="Menu" class="nav-toggle">
    <svg width="18" height="14" viewBox="0 0 18 14" fill="none" aria-hidden="true"><path d="M1 1 H17 M1 7 H17 M1 13 H17" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/></svg>
  </button>
  <div data-nav-menu id="${menuId}" class="nav-menu">
    <div class="nav-links" style="display: flex; align-items: center; gap: 22px; font-family: 'Hanken Grotesk', sans-serif; font-size: 14px; color: rgba(250, 251, 255,0.72);">
      <a href="/network/">Network</a>
      <a href="/blog/" style="color: #FAFBFF;">Blog</a>
      <a href="/#token">$MALIBU</a>
      <a href="https://malibu.tech/docs">Docs</a>
      <a href="/console/">Console</a>
    </div>
    <a href="/host/" class="nav-cta">
      Host a model
      <svg width="11" height="8" viewBox="0 0 14 10" fill="none" aria-hidden="true"><path d="M1 5 H13 M9 1 L13 5 L9 9" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/></svg>
    </a>
  </div>
</nav>`;

const footer = () => `  <footer style="position: relative; overflow: hidden; background: #0C3A45; color: #FAFBFF; padding: clamp(64px, 8vh, 96px) clamp(28px, 5vw, 80px) 48px;">
    <div style="position: relative; max-width: 1240px; margin: 0 auto;">
      <div style="display: flex; justify-content: space-between; align-items: flex-start; gap: 48px 32px; flex-wrap: wrap;">
        <div>
          <div style="font-family: 'JetBrains Mono', monospace; font-size: 10px; letter-spacing: 0.22em; text-transform: uppercase; color: #FFC629; margin-bottom: 22px;">Product</div>
          <div style="display: flex; flex-direction: column; gap: 12px; font-size: 14px; color: rgba(250, 251, 255,0.78);">
            <a href="/console/">Console</a>
            <a href="/host/">Host a model</a>
            <a href="/network/">Network</a>
            <a href="/#token">$MALIBU</a>
          </div>
        </div>
        <div>
          <div style="font-family: 'JetBrains Mono', monospace; font-size: 10px; letter-spacing: 0.22em; text-transform: uppercase; color: #FFC629; margin-bottom: 22px;">Learn</div>
          <div style="display: flex; flex-direction: column; gap: 12px; font-size: 14px; color: rgba(250, 251, 255,0.78);">
            <a href="/blog/">Blog</a>
            <a href="https://malibu.tech/docs">Docs</a>
            <a href="https://malibu.tech/docs/litepaper">Litepaper</a>
            <a href="https://github.com/Augustas11/macprovider" target="_blank" rel="noopener">GitHub</a>
          </div>
        </div>
      </div>
      <div style="display: flex; align-items: center; justify-content: space-between; gap: 24px; flex-wrap: wrap; margin-top: 64px; padding-top: 32px; border-top: 1px solid rgba(250, 251, 255,0.08); font-family: 'JetBrains Mono', monospace; font-size: 10px; letter-spacing: 0.2em; text-transform: uppercase; color: rgba(250, 251, 255,0.66);">
        <div>© 2026 Malibu AI, Inc.</div>
        <a href="/">Back to Malibu →</a>
      </div>
    </div>
  </footer>`;

// ---------------------------------------------------------------------------
// Post page
// ---------------------------------------------------------------------------

const POST_STYLE = `  <style>
    .post-wrap { max-width: 720px; margin: 0 auto; }
    .post-eyebrow { font-family: 'JetBrains Mono', monospace; font-size: 10px; letter-spacing: 0.28em; text-transform: uppercase; color: #FFC629; margin-bottom: 18px; display: flex; gap: 18px; }
    .post-title { font-family: 'Hanken Grotesk', sans-serif; font-weight: 500; font-size: clamp(40px, 6vw, 76px); line-height: 0.98; letter-spacing: -0.03em; color: #FAFBFF; margin: 0 0 24px; }
    .post-lede { font-family: 'Hanken Grotesk', sans-serif; font-size: clamp(18px, 1.5vw, 22px); line-height: 1.5; color: rgba(250, 251, 255,0.82); margin: 0; }
    .post-byline { display: flex; flex-wrap: wrap; gap: 8px 14px; margin: 26px 0 0; font-family: 'JetBrains Mono', monospace; font-size: 11px; letter-spacing: 0.14em; text-transform: uppercase; color: rgba(250, 251, 255,0.6); }
    .post-byline .sep { color: rgba(250, 251, 255,0.3); }
    .post-byline strong { color: rgba(250, 251, 255,0.82); font-weight: 500; }
    .post-toc { margin: 0 0 44px; padding: 22px 26px; border: 1px solid rgba(250, 251, 255,0.1); border-radius: 16px; background: rgba(250, 251, 255,0.03); }
    .post-toc-label { font-family: 'JetBrains Mono', monospace; font-size: 10px; letter-spacing: 0.22em; text-transform: uppercase; color: #FFC629; margin-bottom: 14px; }
    .post-toc ul { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 9px; }
    .post-toc li { margin: 0; }
    .post-toc a { font-family: 'Hanken Grotesk', sans-serif; font-size: 15px; line-height: 1.4; color: rgba(250, 251, 255,0.72); text-decoration: none; }
    .post-toc a:hover { color: #FF8672; }
    .post-body { font-family: 'Hanken Grotesk', sans-serif; font-size: 18px; line-height: 1.65; color: rgba(250, 251, 255,0.86); }
    .post-body p { margin: 0 0 22px; }
    .post-body h2 { font-family: 'Hanken Grotesk', sans-serif; font-weight: 500; font-size: clamp(28px, 3vw, 36px); line-height: 1.15; letter-spacing: -0.02em; color: #FAFBFF; margin: 56px 0 20px; scroll-margin-top: 96px; }
    .post-body h3 { font-family: 'Hanken Grotesk', sans-serif; font-weight: 600; font-size: 22px; line-height: 1.2; color: #FAFBFF; margin: 40px 0 16px; scroll-margin-top: 96px; }
    .post-body strong { color: #FAFBFF; font-weight: 600; }
    .post-body em { font-style: italic; }
    .post-body ul { margin: 0 0 22px; padding: 0 0 0 22px; }
    .post-body li { margin: 0 0 12px; }
    .post-body li strong { color: #F76B57; font-weight: 600; }
    .post-body a { color: #FF8672; text-decoration: underline; text-decoration-color: rgba(255, 134, 114,0.4); text-underline-offset: 3px; }
    .post-body a:hover { text-decoration-color: #FF8672; }
    .post-body pre { margin: 0 0 26px; padding: 22px 24px; background: rgba(12, 58, 69,0.55); border: 1px solid rgba(250, 251, 255,0.08); border-radius: 14px; overflow-x: auto; font-family: 'JetBrains Mono', monospace; font-size: 13.5px; line-height: 1.55; color: rgba(250, 251, 255,0.9); }
    .post-body pre code { background: none; padding: 0; font-size: inherit; color: inherit; }
    .post-body code { font-family: 'JetBrains Mono', monospace; font-size: 0.88em; padding: 2px 6px; background: rgba(250, 251, 255,0.08); border-radius: 5px; color: #FFC629; }
    .post-hr { border: 0; height: 1px; background: rgba(250, 251, 255,0.1); margin: 56px 0 40px; }
    .post-faq { margin: 56px 0 0; }
    .post-faq .faq-item { padding: 22px 0; border-top: 1px solid rgba(250, 251, 255,0.1); }
    .post-faq .faq-item:last-child { border-bottom: 1px solid rgba(250, 251, 255,0.1); }
    .post-faq .faq-item h3 { margin: 0 0 10px; }
    .post-faq .faq-item p { margin: 0; color: rgba(250, 251, 255,0.78); }
    .post-howto { margin: 56px 0 0; }
    .post-howto .howto-steps { margin: 0; padding: 0 0 0 24px; counter-reset: howto; }
    .post-howto .howto-steps li { margin: 0 0 14px; padding-left: 6px; }
    .post-howto .howto-steps li strong { color: #F76B57; font-weight: 600; }
    .post-cta-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-top: 8px; }
    @media (max-width: 640px) { .post-cta-grid { grid-template-columns: 1fr; } }
    .post-cta { display: block; padding: 24px 26px; border-radius: 18px; border: 1px solid rgba(250, 251, 255,0.12); background: rgba(250, 251, 255,0.04); transition: border-color 200ms ease, background 200ms ease, transform 200ms ease; }
    .post-cta:hover { border-color: rgba(247, 107, 87,0.5); background: rgba(250, 251, 255,0.06); transform: translateY(-2px); }
    .post-cta-label { font-family: 'JetBrains Mono', monospace; font-size: 10px; letter-spacing: 0.22em; text-transform: uppercase; color: #FFC629; margin-bottom: 10px; }
    .post-cta-title { font-family: 'Hanken Grotesk', sans-serif; font-size: 20px; font-weight: 500; letter-spacing: -0.01em; color: #FAFBFF; }
    .post-cta-sub { font-family: 'Hanken Grotesk', sans-serif; font-size: 14px; color: rgba(250, 251, 255,0.65); margin-top: 6px; }
    .post-back { display: inline-flex; align-items: center; gap: 8px; font-family: 'JetBrains Mono', monospace; font-size: 10px; letter-spacing: 0.22em; text-transform: uppercase; color: rgba(250, 251, 255,0.6); margin-bottom: 40px; }
    .post-back:hover { color: #FAFBFF; }
    .post-hero { margin: 40px 0 0; border-radius: 20px; overflow: hidden; border: 1px solid rgba(250, 251, 255,0.08); box-shadow: 0 30px 80px -30px rgba(0,0,0,0.55); background: #0C3A45; }
    .post-hero img { display: block; width: 100%; height: auto; }
    @media (max-width: 640px) { .post-hero { border-radius: 14px; margin-top: 32px; } }
  </style>`;

function jsonLd(post) {
  const article = {
    '@context': 'https://schema.org',
    '@type': 'BlogPosting',
    headline: post.title,
    description: post.description,
    image: post.ogImage,
    datePublished: post.date,
    dateModified: post.dateModified,
    author: { '@type': 'Organization', name: post.author, url: SITE },
    publisher: {
      '@type': 'Organization',
      name: 'Malibu AI, Inc.',
      logo: { '@type': 'ImageObject', url: `${SITE}/favicon.png` },
    },
    mainEntityOfPage: { '@type': 'WebPage', '@id': post.canonical },
  };
  if (post.keywords.length) article.keywords = post.keywords.join(', ');
  const breadcrumb = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Malibu', item: `${SITE}/` },
      { '@type': 'ListItem', position: 2, name: 'Blog', item: `${SITE}/blog/` },
      { '@type': 'ListItem', position: 3, name: post.title, item: post.canonical },
    ],
  };
  const blocks = [article, breadcrumb];

  // Opt-in FAQ/HowTo — only emitted when the post supplies matching frontmatter,
  // so structured data never claims content the page doesn't have.
  if (post.faq.length) {
    blocks.push({
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: post.faq.map((f) => ({
        '@type': 'Question',
        name: f.q,
        acceptedAnswer: { '@type': 'Answer', text: f.a },
      })),
    });
  }
  if (post.howto) {
    const howto = {
      '@context': 'https://schema.org',
      '@type': 'HowTo',
      name: post.howto.name || post.title,
      step: post.howto.steps.map((s, i) => ({
        '@type': 'HowToStep',
        position: i + 1,
        ...(s.name ? { name: s.name } : {}),
        text: s.text,
      })),
    };
    if (post.howto.totalTime) howto.totalTime = post.howto.totalTime;
    blocks.push(howto);
  }

  return blocks
    .map((o) => `  <script type="application/ld+json">\n${jsonForScript(o)}\n  </script>`)
    .join('\n');
}

function renderPost(post) {
  const hero = post.heroImage
    ? `      <figure class="post-hero">
        <img src="${escAttr(post.heroImage)}" alt="${escAttr(post.heroAlt)}" width="1280" height="714" loading="eager" fetchpriority="high" />
      </figure>\n`
    : '';
  const keywordsMeta = post.keywords.length
    ? `  <meta name="keywords" content="${escAttr(post.keywords.join(', '))}" />\n`
    : '';
  const ogDims = post.isDefaultHero
    ? `  <meta property="og:image:width" content="1280" />\n  <meta property="og:image:height" content="714" />\n`
    : '';
  const byline = `      <div class="post-byline">
        <span>By <strong>${escText(post.author)}</strong></span>${
          post.dateDisplay ? `\n        <span class="sep">·</span>\n        <span>${escText(post.dateDisplay)}</span>` : ''
        }
        <span class="sep">·</span>
        <span>${post.readingTime} min read</span>
      </div>`;
  // TOC covers body headings plus the generated HowTo/FAQ sections, so the
  // "jump to any section" list doesn't miss them.
  const howtoHeading = post.howto ? post.howto.name || 'Steps' : '';
  const tocEntries = [
    ...post.toc,
    ...(post.howto ? [{ text: howtoHeading, id: 'steps' }] : []),
    ...(post.faq.length ? [{ text: 'Frequently asked questions', id: 'faq' }] : []),
  ];
  const toc =
    tocEntries.length >= 3
      ? `      <nav class="post-toc" aria-label="On this page">
        <div class="post-toc-label">On this page</div>
        <ul>
${tocEntries.map((h) => `          <li><a href="#${escAttr(h.id)}">${escText(h.text)}</a></li>`).join('\n')}
        </ul>
      </nav>\n`
      : '';
  // Render HowTo steps visibly from the same data that feeds the HowTo JSON-LD,
  // so the structured data always describes content that's actually on the page.
  const howtoSection = post.howto
    ? `
      <section class="post-howto" id="steps" aria-labelledby="howto-heading">
        <h2 id="howto-heading">${escText(howtoHeading)}</h2>
        <ol class="howto-steps">
${post.howto.steps
  .map(
    (s) =>
      `          <li>${s.name ? `<strong>${escText(s.name)}.</strong> ` : ''}${escText(s.text)}</li>`,
  )
  .join('\n')}
        </ol>
      </section>\n`
    : '';
  // Render the FAQ visibly from the same data that feeds the FAQPage JSON-LD.
  const faqSection = post.faq.length
    ? `
      <section class="post-faq" id="faq" aria-labelledby="faq-heading">
        <h2 id="faq-heading">Frequently asked questions</h2>
${post.faq
  .map(
    (f) => `        <div class="faq-item">
          <h3 id="${escAttr(slugify(f.q))}">${escText(f.q)}</h3>
          <p>${escText(f.a)}</p>
        </div>`,
  )
  .join('\n')}
      </section>\n`
    : '';
  return `<!doctype html>
<html lang="en">
${BANNER(post.slug)}
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="${escAttr(post.description)}" />
${keywordsMeta}  <link rel="canonical" href="${escAttr(post.canonical)}" />
  <meta property="og:title" content="${escAttr(post.ogTitle)}" />
  <meta property="og:description" content="${escAttr(post.ogDescription)}" />
  <meta property="og:type" content="article" />
  <meta property="og:url" content="${escAttr(post.canonical)}" />
  <meta property="og:image" content="${escAttr(post.ogImage)}" />
${ogDims}  <meta property="article:published_time" content="${escAttr(post.date)}" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="${escAttr(post.ogTitle)}" />
  <meta name="twitter:description" content="${escAttr(post.ogDescription)}" />
  <meta name="twitter:image" content="${escAttr(post.ogImage)}" />
  <title>${escText(post.title)} · Malibu</title>
${HEAD_ASSETS}
${jsonLd(post)}
${POST_STYLE}
</head>
<body>

<!-- ============ FLOATING NAV ============ -->
${nav('post-nav-menu')}

<main id="top" style="background: #143A45; color: #FAFBFF; min-height: 100vh;">

  <!-- ============ ARTICLE HEADER ============ -->
  <section style="position: relative; padding: clamp(120px, 18vh, 200px) clamp(20px, 5vw, 80px) clamp(32px, 4vh, 56px);">
    <div aria-hidden="true" style="position: absolute; top: 0; left: 30%; right: 30%; height: 260px; background: radial-gradient(ellipse at top, rgba(247, 107, 87,0.18), transparent 70%); pointer-events: none;"></div>
    <div class="post-wrap" style="position: relative;">
      <a href="/blog/" class="post-back">
        <svg width="10" height="8" viewBox="0 0 14 10" fill="none" aria-hidden="true"><path d="M13 5 H1 M5 1 L1 5 L5 9" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/></svg>
        Blog
      </a>
      <div class="post-eyebrow">
        <span>${escText(post.category)}</span>
      </div>
      <h1 class="post-title">${escText(post.headline)}</h1>
      <p class="post-lede">${escText(post.lede)}</p>
${byline}
${hero}    </div>
  </section>

  <!-- ============ ARTICLE BODY ============ -->
  <section style="position: relative; padding: 0 clamp(20px, 5vw, 80px) clamp(72px, 10vh, 120px);">
    <div class="post-wrap post-body">

${toc}${post.bodyHtml}
${howtoSection}${faqSection}
      <hr class="post-hr" />

      <div class="post-cta-grid">
        <a href="/host/" class="post-cta">
          <div class="post-cta-label">Own a Mac?</div>
          <div class="post-cta-title">Host a model →</div>
          <div class="post-cta-sub">One command. Zero configuration. Earning from the first request.</div>
        </a>
        <a href="/console/" class="post-cta">
          <div class="post-cta-label">Buy inference?</div>
          <div class="post-cta-title">Open the console →</div>
          <div class="post-cta-sub">Point your OpenAI SDK at Malibu. Nothing else changes.</div>
        </a>
      </div>

    </div>
  </section>

  <!-- ============ FOOTER ============ -->
${footer()}
</main>

<script type="module" src="/src/nav.js"></script>
</body>
</html>
`;
}

// ---------------------------------------------------------------------------
// Index page
// ---------------------------------------------------------------------------

const INDEX_STYLE = `  <style>
    .blog-list { display: flex; flex-direction: column; gap: 24px; }
    .blog-card { display: block; padding: 32px clamp(24px, 3vw, 44px); border-radius: 20px; background: rgba(250, 251, 255,0.04); border: 1px solid rgba(250, 251, 255,0.08); transition: background 200ms ease, border-color 200ms ease, transform 200ms ease; }
    .blog-card:hover { background: rgba(250, 251, 255,0.06); border-color: rgba(247, 107, 87,0.4); transform: translateY(-2px); }
    .blog-card-meta { font-family: 'JetBrains Mono', monospace; font-size: 10px; letter-spacing: 0.24em; text-transform: uppercase; color: #FFC629; margin-bottom: 14px; display: flex; flex-wrap: wrap; gap: 8px 18px; }
    .blog-card-meta .date { color: rgba(250, 251, 255,0.55); }
    .blog-card-title { font-family: 'Hanken Grotesk', sans-serif; font-weight: 500; font-size: clamp(24px, 2.6vw, 34px); line-height: 1.15; letter-spacing: -0.02em; color: #FAFBFF; margin: 0 0 12px; }
    .blog-card-excerpt { font-family: 'Hanken Grotesk', sans-serif; font-size: 16px; line-height: 1.55; color: rgba(250, 251, 255,0.72); margin: 0; max-width: 68ch; }
    .blog-card-more { display: inline-flex; align-items: center; gap: 8px; margin-top: 20px; font-family: 'JetBrains Mono', monospace; font-size: 11px; letter-spacing: 0.18em; text-transform: uppercase; color: #F76B57; }
  </style>`;

function renderIndexCard(post) {
  const date = post.dateDisplay
    ? `\n            <span class="date">${escText(post.dateDisplay)}</span>`
    : '';
  return `        <a href="/blog/${post.slug}/" class="blog-card">
          <div class="blog-card-meta">
            <span>${escText(post.category)}</span>${date}
          </div>
          <h2 class="blog-card-title">${escText(post.title)}</h2>
          <p class="blog-card-excerpt">${escText(post.excerpt)}</p>
          <span class="blog-card-more">
            Read the post
            <svg width="11" height="8" viewBox="0 0 14 10" fill="none" aria-hidden="true"><path d="M1 5 H13 M9 1 L13 5 L9 9" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/></svg>
          </span>
        </a>`;
}

function indexJsonLd(posts) {
  const blog = {
    '@context': 'https://schema.org',
    '@type': 'Blog',
    name: 'Malibu · Blog',
    url: `${SITE}/blog/`,
    description:
      "Network updates, engineering notes, and the ideas behind turning idle Apple Silicon into the world's biggest AI cloud.",
    publisher: {
      '@type': 'Organization',
      name: 'Malibu AI, Inc.',
      logo: { '@type': 'ImageObject', url: `${SITE}/favicon.png` },
    },
    blogPost: posts.map((p) => ({
      '@type': 'BlogPosting',
      headline: p.title,
      url: p.canonical,
      datePublished: p.date,
      author: { '@type': 'Organization', name: p.author },
    })),
  };
  const breadcrumb = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Malibu', item: `${SITE}/` },
      { '@type': 'ListItem', position: 2, name: 'Blog', item: `${SITE}/blog/` },
    ],
  };
  return (
    `  <script type="application/ld+json">\n${jsonForScript(blog)}\n  </script>\n` +
    `  <script type="application/ld+json">\n${jsonForScript(breadcrumb)}\n  </script>`
  );
}

function renderIndex(posts) {
  const cards = posts.length
    ? posts.map(renderIndexCard).join('\n\n')
    : '        <p style="font-family: \'Hanken Grotesk\', sans-serif; color: rgba(250, 251, 255,0.6);">No posts yet.</p>';
  return `<!doctype html>
<html lang="en">
<!-- ${BANNER_MARK} — do not edit directly. -->
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="Writing from the Malibu team — network updates, engineering notes, and the ideas behind turning idle Apple Silicon into the world's largest AI cloud." />
  <link rel="canonical" href="${SITE}/blog/" />
  <meta property="og:title" content="Malibu · Blog" />
  <meta property="og:description" content="Writing from the Malibu team — network updates, engineering notes, and the ideas behind the network." />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="${SITE}/blog/" />
  <title>Malibu Blog · Apple Silicon AI inference and network notes</title>
${HEAD_ASSETS}
${indexJsonLd(posts)}
${INDEX_STYLE}
</head>
<body>

<!-- ============ FLOATING NAV ============ -->
${nav('blog-nav-menu')}

<main id="top" style="background: #143A45; color: #FAFBFF; min-height: 100vh;">

  <!-- ============ HEADER ============ -->
  <section style="position: relative; padding: clamp(120px, 18vh, 200px) clamp(20px, 5vw, 80px) clamp(48px, 6vh, 72px);">
    <div aria-hidden="true" style="position: absolute; top: 0; left: 30%; right: 30%; height: 260px; background: radial-gradient(ellipse at top, rgba(247, 107, 87,0.18), transparent 70%); pointer-events: none;"></div>
    <div style="position: relative; max-width: 900px; margin: 0 auto;">
      <div style="font-family: 'JetBrains Mono', monospace; font-size: 10px; letter-spacing: 0.28em; text-transform: uppercase; color: #FFC629; margin-bottom: 18px;">The Malibu blog</div>
      <h1 style="font-family: 'Hanken Grotesk', sans-serif; font-weight: 500; font-size: clamp(56px, 8vw, 128px); line-height: 0.9; letter-spacing: -0.035em; color: #FAFBFF; margin: 0;">
        Writing <em style="font-style: normal; color: #F76B57;">from the network.</em>
      </h1>
      <p style="font-family: 'Hanken Grotesk', sans-serif; font-size: clamp(16px, 1.4vw, 20px); line-height: 1.5; color: rgba(250, 251, 255,0.72); margin: 22px 0 0; max-width: 60ch;">
        Network updates, engineering notes, and the ideas behind turning every idle Apple Silicon Mac into part of the world's biggest AI cloud.
      </p>
    </div>
  </section>

  <!-- ============ POSTS ============ -->
  <section style="position: relative; padding: 0 clamp(20px, 5vw, 80px) clamp(96px, 14vh, 160px);">
    <div style="position: relative; max-width: 900px; margin: 0 auto;">
      <div class="blog-list">

${cards}

      </div>
    </div>
  </section>

  <!-- ============ FOOTER ============ -->
${footer()}
</main>

<script type="module" src="/src/nav.js"></script>
</body>
</html>
`;
}

// ---------------------------------------------------------------------------
// sitemap.xml + feed.xml
// ---------------------------------------------------------------------------

function renderSitemap(posts) {
  const staticRoutes = ['/', '/blog/', '/network/', '/host/'];
  const urls = [
    ...staticRoutes.map((path) => `  <url>\n    <loc>${escXml(SITE + path)}</loc>\n  </url>`),
    ...posts.map(
      (p) =>
        `  <url>\n    <loc>${escXml(`${SITE}/blog/${p.slug}/`)}</loc>\n    <lastmod>${escXml(p.dateModified)}</lastmod>\n  </url>`,
    ),
  ];
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.join('\n')}
</urlset>
`;
}

function renderFeed(posts) {
  const items = posts
    .map(
      (p) => `    <item>
      <title>${escXml(p.title)}</title>
      <link>${escXml(p.canonical)}</link>
      <guid isPermaLink="true">${escXml(p.canonical)}</guid>
      <pubDate>${new Date(p.date).toUTCString()}</pubDate>
      <description>${escXml(p.description || p.excerpt)}</description>
    </item>`,
    )
    .join('\n');
  const lastBuild = posts.length ? new Date(posts[0].date).toUTCString() : new Date(0).toUTCString();
  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Malibu · Blog</title>
    <link>${SITE}/blog/</link>
    <description>Network updates, engineering notes, and the ideas behind turning idle Apple Silicon into the world's biggest AI cloud.</description>
    <language>en-us</language>
    <lastBuildDate>${lastBuild}</lastBuildDate>
    <atom:link href="${SITE}/blog/feed.xml" rel="self" type="application/rss+xml" />
${items}
  </channel>
</rss>
`;
}

// ---------------------------------------------------------------------------
// Prune generated pages whose source post is gone or newly a draft.
// Only ever removes dirs WE generated (identified by the banner marker).
// ---------------------------------------------------------------------------

function pruneOrphans(publishedSlugs) {
  for (const entry of readdirSync(blogDir, { withFileTypes: true })) {
    if (!entry.isDirectory() || entry.name === 'posts') continue;
    if (publishedSlugs.has(entry.name)) continue;
    const page = join(blogDir, entry.name, 'index.html');
    if (!existsSync(page)) continue;
    if (readFileSync(page, 'utf8').includes(BANNER_MARK)) {
      rmSync(join(blogDir, entry.name), { recursive: true, force: true });
      console.log(`build-blog: pruned orphan blog/${entry.name}/`);
    }
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  const posts = loadPosts();
  const publishedSlugs = new Set(posts.map((p) => p.slug));

  pruneOrphans(publishedSlugs);

  for (const post of posts) {
    const dir = join(blogDir, post.slug);
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, 'index.html'), renderPost(post));
  }

  writeFileSync(join(blogDir, 'index.html'), renderIndex(posts));
  writeFileSync(join(publicDir, 'sitemap.xml'), renderSitemap(posts));
  mkdirSync(join(publicDir, 'blog'), { recursive: true });
  writeFileSync(join(publicDir, 'blog', 'feed.xml'), renderFeed(posts));

  console.log(
    `build-blog: ${posts.length} post(s) → blog/<slug>/index.html, blog/index.html, sitemap.xml, blog/feed.xml`,
  );
}

main();
