#!/usr/bin/env node
/**
 * Build the Malibu blog from Markdown sources.
 *
 * Source of truth:  blog/posts/<slug>.md   (frontmatter + Markdown body)
 * Generated:        blog/<slug>/index.html (one per post, a Vite input via glob)
 *                   blog/index.html         (post listing)
 *                   public/sitemap.xml      (served at /sitemap.xml)
 *                   public/blog/feed.xml    (served at /blog/feed.xml)
 *
 * Adding a post = add one Markdown file and run `npm run blog:build`.
 * Never edit the generated files or vite.config.js by hand.
 */
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from 'node:fs';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const postsDir = join(root, 'blog', 'posts');
const blogDir = join(root, 'blog');
const publicDir = join(root, 'public');

const SITE = 'https://malibu.tech';
const BANNER = (slug) =>
  `<!-- GENERATED by scripts/build-blog.mjs from blog/posts/${slug}.md — do not edit directly. -->`;

marked.setOptions({ gfm: true, breaks: false });

// ---------------------------------------------------------------------------
// Parsing helpers
// ---------------------------------------------------------------------------

function parseFrontmatter(raw) {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!m) return { data: {}, body: raw };
  const data = {};
  for (const line of m[1].split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = line.indexOf(':');
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    let val = line.slice(idx + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    if (val.startsWith('[') && val.endsWith(']')) {
      data[key] = val
        .slice(1, -1)
        .split(',')
        .map((s) => s.trim().replace(/^["']|["']$/g, ''))
        .filter(Boolean);
    } else if (val === 'true' || val === 'false') {
      data[key] = val === 'true';
    } else {
      data[key] = val;
    }
  }
  return { data, body: m[2] };
}

const escAttr = (s = '') =>
  String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

const escText = (s = '') =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

function loadPosts() {
  if (!existsSync(postsDir)) return [];
  const posts = readdirSync(postsDir)
    .filter((f) => f.endsWith('.md'))
    .map((file) => {
      const slug = basename(file, '.md');
      const raw = readFileSync(join(postsDir, file), 'utf8');
      const { data, body } = parseFrontmatter(raw);
      if (!data.title || !data.date) {
        throw new Error(`blog/posts/${file}: missing required frontmatter (title, date)`);
      }
      const canonical = data.canonical || `${SITE}/blog/${slug}/`;
      // OG/Twitter/JSON-LD images must be absolute URLs for social unfurls.
      const rawOgImage =
        data.ogImage || data.heroImage || '/images/brand/blog-hero-macbook-sunset-mesh.jpg';
      const ogImage = rawOgImage.startsWith('/') ? `${SITE}${rawOgImage}` : rawOgImage;
      return {
        slug,
        title: data.title,
        headline: data.headline || data.title,
        category: data.category || 'Notes',
        date: data.date,
        description: data.description || data.lede || '',
        ogTitle: data.ogTitle || data.title,
        ogDescription: data.ogDescription || data.description || data.lede || '',
        ogImage,
        lede: data.lede || '',
        excerpt: data.excerpt || data.lede || data.description || '',
        heroImage: data.heroImage || '',
        heroAlt: data.heroAlt || '',
        keywords: data.keywords || [],
        canonical,
        draft: data.draft === true,
        bodyHtml: marked.parse(body.trim()),
      };
    })
    .filter((p) => !p.draft)
    .sort((a, b) => new Date(b.date) - new Date(a.date));
  return posts;
}

// ---------------------------------------------------------------------------
// Shared chrome (kept byte-identical to the hand-authored pages)
// ---------------------------------------------------------------------------

const HEAD_ASSETS = `  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Hanken+Grotesk:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet" />
  <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
  <link rel="alternate" type="application/rss+xml" title="Malibu · Blog" href="/blog/feed.xml" />
  <link rel="stylesheet" href="/src/styles.css" />`;

const nav = (menuId, blogActive) => `<nav data-nav-pill aria-label="Primary navigation" style="position: fixed; top: 22px; left: 50%; transform: translateX(-50%); z-index: 100; display: flex; align-items: center; gap: 28px; height: 56px; padding: 0 10px 0 20px; background: #143A45; border-radius: 9999px; box-shadow: 0 18px 50px -22px rgba(20, 58, 69,0.55), 0 2px 6px rgba(20, 58, 69,0.18);">
  <a href="/" style="display: flex; align-items: center; gap: 10px; padding-right: 10px; border-right: 1px solid rgba(255, 251, 242,0.12); flex-shrink: 0;">
    <span style="display: inline-flex; align-items: center; justify-content: center; width: 28px; height: 28px; border-radius: 50%; background: #0C3A45;">
      <svg width="18" height="13" viewBox="0 0 44 32" aria-hidden="true">
        <line x1="2" y1="22" x2="42" y2="22" stroke="#FFFBF2" stroke-width="2" stroke-linecap="round"/>
        <path d="M10 22 a12 12 0 0 1 24 0 Z" fill="#FFFBF2"/>
      </svg>
    </span>
    <span style="font-family: 'Hanken Grotesk', sans-serif; font-size: 17px; font-weight: 500; letter-spacing: -0.01em; color: #FFFBF2; line-height: 1;">malibu</span>
  </a>
  <button type="button" data-nav-toggle aria-expanded="false" aria-controls="${menuId}" aria-label="Menu" class="nav-toggle">
    <svg width="18" height="14" viewBox="0 0 18 14" fill="none" aria-hidden="true"><path d="M1 1 H17 M1 7 H17 M1 13 H17" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/></svg>
  </button>
  <div data-nav-menu id="${menuId}" class="nav-menu">
    <div class="nav-links" style="display: flex; align-items: center; gap: 22px; font-family: 'Hanken Grotesk', sans-serif; font-size: 14px; color: rgba(255, 251, 242,0.72);">
      <a href="/network/">Network</a>
      <a href="/blog/"${blogActive ? ' style="color: #FFFBF2;"' : ''}>Blog</a>
      <a href="/#token">$MALIBU</a>
      <a href="https://malibu.tech/docs">Docs</a>
      <a href="/console/">Console</a>
    </div>
    <a href="/host/" class="nav-cta">
      Host a model
      <svg width="11" height="8" viewBox="0 0 14 10" fill="none" aria-hidden="true"><path d="M1 5 H13 M9 1 L13 5 L9 9" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/></svg>
    </a>
  </div>
</nav>`;

const footer = () => `  <footer style="position: relative; overflow: hidden; background: #0C3A45; color: #FFFBF2; padding: clamp(64px, 8vh, 96px) clamp(28px, 5vw, 80px) 48px;">
    <div style="position: relative; max-width: 1240px; margin: 0 auto;">
      <div style="display: flex; justify-content: space-between; align-items: flex-start; gap: 48px 32px; flex-wrap: wrap;">
        <div>
          <div style="font-family: 'JetBrains Mono', monospace; font-size: 10px; letter-spacing: 0.22em; text-transform: uppercase; color: #FFC629; margin-bottom: 22px;">Product</div>
          <div style="display: flex; flex-direction: column; gap: 12px; font-size: 14px; color: rgba(255, 251, 242,0.78);">
            <a href="/console/">Console</a>
            <a href="/host/">Host a model</a>
            <a href="/network/">Network</a>
            <a href="/#token">$MALIBU</a>
          </div>
        </div>
        <div>
          <div style="font-family: 'JetBrains Mono', monospace; font-size: 10px; letter-spacing: 0.22em; text-transform: uppercase; color: #FFC629; margin-bottom: 22px;">Learn</div>
          <div style="display: flex; flex-direction: column; gap: 12px; font-size: 14px; color: rgba(255, 251, 242,0.78);">
            <a href="/blog/">Blog</a>
            <a href="https://malibu.tech/docs">Docs</a>
            <a href="https://malibu.tech/docs/litepaper">Litepaper</a>
            <a href="https://github.com/Augustas11/macprovider" target="_blank" rel="noopener">GitHub</a>
          </div>
        </div>
      </div>
      <div style="display: flex; align-items: center; justify-content: space-between; gap: 24px; flex-wrap: wrap; margin-top: 64px; padding-top: 32px; border-top: 1px solid rgba(255, 251, 242,0.08); font-family: 'JetBrains Mono', monospace; font-size: 10px; letter-spacing: 0.2em; text-transform: uppercase; color: rgba(255, 251, 242,0.5);">
        <div>© 2026 Malibu AI, Inc.</div>
        <a href="/">Back to malibu →</a>
      </div>
    </div>
  </footer>`;

// ---------------------------------------------------------------------------
// Post page
// ---------------------------------------------------------------------------

const POST_STYLE = `  <style>
    .post-wrap { max-width: 720px; margin: 0 auto; }
    .post-eyebrow { font-family: 'JetBrains Mono', monospace; font-size: 10px; letter-spacing: 0.28em; text-transform: uppercase; color: #FFC629; margin-bottom: 18px; display: flex; gap: 18px; }
    .post-title { font-family: 'Hanken Grotesk', sans-serif; font-weight: 500; font-size: clamp(40px, 6vw, 76px); line-height: 0.98; letter-spacing: -0.03em; color: #FFFBF2; margin: 0 0 24px; }
    .post-lede { font-family: 'Hanken Grotesk', sans-serif; font-size: clamp(18px, 1.5vw, 22px); line-height: 1.5; color: rgba(255, 251, 242,0.82); margin: 0; }
    .post-body { font-family: 'Hanken Grotesk', sans-serif; font-size: 18px; line-height: 1.65; color: rgba(255, 251, 242,0.86); }
    .post-body p { margin: 0 0 22px; }
    .post-body h2 { font-family: 'Hanken Grotesk', sans-serif; font-weight: 500; font-size: clamp(28px, 3vw, 36px); line-height: 1.15; letter-spacing: -0.02em; color: #FFFBF2; margin: 56px 0 20px; }
    .post-body strong { color: #FFFBF2; font-weight: 600; }
    .post-body em { font-style: italic; }
    .post-body ul { margin: 0 0 22px; padding: 0 0 0 22px; }
    .post-body li { margin: 0 0 12px; }
    .post-body li strong { color: #FF6E5B; font-weight: 600; }
    .post-body a { color: #FF6E5B; text-decoration: underline; text-decoration-color: rgba(255, 110, 91,0.35); text-underline-offset: 3px; }
    .post-body a:hover { text-decoration-color: #FF6E5B; }
    .post-body pre { margin: 0 0 26px; padding: 22px 24px; background: rgba(12, 58, 69,0.55); border: 1px solid rgba(255, 251, 242,0.08); border-radius: 14px; overflow-x: auto; font-family: 'JetBrains Mono', monospace; font-size: 13.5px; line-height: 1.55; color: rgba(255, 251, 242,0.9); }
    .post-body pre code { background: none; padding: 0; font-size: inherit; color: inherit; }
    .post-body code { font-family: 'JetBrains Mono', monospace; font-size: 0.88em; padding: 2px 6px; background: rgba(255, 251, 242,0.08); border-radius: 5px; color: #FFC629; }
    .post-hr { border: 0; height: 1px; background: rgba(255, 251, 242,0.1); margin: 56px 0 40px; }
    .post-cta-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-top: 8px; }
    @media (max-width: 640px) { .post-cta-grid { grid-template-columns: 1fr; } }
    .post-cta { display: block; padding: 24px 26px; border-radius: 18px; border: 1px solid rgba(255, 251, 242,0.12); background: rgba(255, 251, 242,0.04); transition: border-color 200ms ease, background 200ms ease, transform 200ms ease; }
    .post-cta:hover { border-color: rgba(255, 110, 91,0.5); background: rgba(255, 251, 242,0.06); transform: translateY(-2px); }
    .post-cta-label { font-family: 'JetBrains Mono', monospace; font-size: 10px; letter-spacing: 0.22em; text-transform: uppercase; color: #FFC629; margin-bottom: 10px; }
    .post-cta-title { font-family: 'Hanken Grotesk', sans-serif; font-size: 20px; font-weight: 500; letter-spacing: -0.01em; color: #FFFBF2; }
    .post-cta-sub { font-family: 'Hanken Grotesk', sans-serif; font-size: 14px; color: rgba(255, 251, 242,0.65); margin-top: 6px; }
    .post-back { display: inline-flex; align-items: center; gap: 8px; font-family: 'JetBrains Mono', monospace; font-size: 10px; letter-spacing: 0.22em; text-transform: uppercase; color: rgba(255, 251, 242,0.6); margin-bottom: 40px; }
    .post-back:hover { color: #FFFBF2; }
    .post-hero { margin: 40px 0 0; border-radius: 20px; overflow: hidden; border: 1px solid rgba(255, 251, 242,0.08); box-shadow: 0 30px 80px -30px rgba(0,0,0,0.55); background: #0C3A45; }
    .post-hero img { display: block; width: 100%; height: auto; }
    @media (max-width: 640px) { .post-hero { border-radius: 14px; margin-top: 32px; } }
  </style>`;

function jsonLd(post) {
  const data = {
    '@context': 'https://schema.org',
    '@type': 'BlogPosting',
    headline: post.title,
    description: post.description,
    image: post.ogImage,
    datePublished: post.date,
    dateModified: post.date,
    author: { '@type': 'Organization', name: 'Malibu AI, Inc.', url: SITE },
    publisher: {
      '@type': 'Organization',
      name: 'Malibu AI, Inc.',
      logo: { '@type': 'ImageObject', url: `${SITE}/favicon.svg` },
    },
    mainEntityOfPage: { '@type': 'WebPage', '@id': post.canonical },
  };
  if (post.keywords.length) data.keywords = post.keywords.join(', ');
  const breadcrumb = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Malibu', item: `${SITE}/` },
      { '@type': 'ListItem', position: 2, name: 'Blog', item: `${SITE}/blog/` },
      { '@type': 'ListItem', position: 3, name: post.title, item: post.canonical },
    ],
  };
  return (
    `  <script type="application/ld+json">\n${JSON.stringify(data, null, 2)}\n  </script>\n` +
    `  <script type="application/ld+json">\n${JSON.stringify(breadcrumb, null, 2)}\n  </script>`
  );
}

function renderPost(post) {
  const hero = post.heroImage
    ? `      <figure class="post-hero">
        <img src="${escAttr(post.heroImage)}" alt="${escAttr(post.heroAlt)}" width="1280" height="714" loading="eager" fetchpriority="high" />
      </figure>\n`
    : '';
  const keywordsMeta = post.keywords.length
    ? `  <meta name="keywords" content="${escAttr(post.keywords.join(', '))}" />\n`
    : '';
  return `<!doctype html>
<html lang="en">
${BANNER(post.slug)}
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="${escAttr(post.description)}" />
${keywordsMeta}  <link rel="canonical" href="${escAttr(post.canonical)}" />
  <meta property="og:title" content="${escAttr(post.ogTitle)}" />
  <meta property="og:description" content="${escAttr(post.ogDescription)}" />
  <meta property="og:type" content="article" />
  <meta property="og:url" content="${escAttr(post.canonical)}" />
  <meta property="og:image" content="${escAttr(post.ogImage)}" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:image" content="${escAttr(post.ogImage)}" />
  <title>${escText(post.title)} · Malibu</title>
${HEAD_ASSETS}
${jsonLd(post)}
${POST_STYLE}
</head>
<body>

<!-- ============ FLOATING NAV ============ -->
${nav('post-nav-menu', true)}

<main id="top" style="background: #143A45; color: #FFFBF2; min-height: 100vh;">

  <!-- ============ ARTICLE HEADER ============ -->
  <section style="position: relative; padding: clamp(120px, 18vh, 200px) clamp(20px, 5vw, 80px) clamp(32px, 4vh, 56px);">
    <div aria-hidden="true" style="position: absolute; top: 0; left: 30%; right: 30%; height: 260px; background: radial-gradient(ellipse at top, rgba(255, 110, 91,0.18), transparent 70%); pointer-events: none;"></div>
    <div class="post-wrap" style="position: relative;">
      <a href="/blog/" class="post-back">
        <svg width="10" height="8" viewBox="0 0 14 10" fill="none" aria-hidden="true"><path d="M13 5 H1 M5 1 L1 5 L5 9" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/></svg>
        Blog
      </a>
      <div class="post-eyebrow">
        <span>${escText(post.category)}</span>
      </div>
      <h1 class="post-title">${escText(post.headline)}</h1>
      <p class="post-lede">${escText(post.lede)}</p>
${hero}    </div>
  </section>

  <!-- ============ ARTICLE BODY ============ -->
  <section style="position: relative; padding: 0 clamp(20px, 5vw, 80px) clamp(72px, 10vh, 120px);">
    <div class="post-wrap post-body">

${post.bodyHtml}

      <hr class="post-hr" />

      <div class="post-cta-grid">
        <a href="/host/" class="post-cta">
          <div class="post-cta-label">Own a Mac?</div>
          <div class="post-cta-title">Host a model →</div>
          <div class="post-cta-sub">One command. Zero configuration. Earning from the first request.</div>
        </a>
        <a href="/console/" class="post-cta">
          <div class="post-cta-label">Buy inference?</div>
          <div class="post-cta-title">Open the console →</div>
          <div class="post-cta-sub">Point your OpenAI SDK at Malibu. Nothing else changes.</div>
        </a>
      </div>

    </div>
  </section>

  <!-- ============ FOOTER ============ -->
${footer()}
</main>

<script type="module" src="/src/nav.js"></script>
</body>
</html>
`;
}

// ---------------------------------------------------------------------------
// Index page
// ---------------------------------------------------------------------------

const INDEX_STYLE = `  <style>
    .blog-list { display: flex; flex-direction: column; gap: 24px; }
    .blog-card { display: block; padding: 32px clamp(24px, 3vw, 44px); border-radius: 20px; background: rgba(255, 251, 242,0.04); border: 1px solid rgba(255, 251, 242,0.08); transition: background 200ms ease, border-color 200ms ease, transform 200ms ease; }
    .blog-card:hover { background: rgba(255, 251, 242,0.06); border-color: rgba(255, 110, 91,0.4); transform: translateY(-2px); }
    .blog-card-meta { font-family: 'JetBrains Mono', monospace; font-size: 10px; letter-spacing: 0.24em; text-transform: uppercase; color: #FFC629; margin-bottom: 14px; display: flex; gap: 18px; }
    .blog-card-title { font-family: 'Hanken Grotesk', sans-serif; font-weight: 500; font-size: clamp(24px, 2.6vw, 34px); line-height: 1.15; letter-spacing: -0.02em; color: #FFFBF2; margin: 0 0 12px; }
    .blog-card-excerpt { font-family: 'Hanken Grotesk', sans-serif; font-size: 16px; line-height: 1.55; color: rgba(255, 251, 242,0.72); margin: 0; max-width: 68ch; }
    .blog-card-more { display: inline-flex; align-items: center; gap: 8px; margin-top: 20px; font-family: 'JetBrains Mono', monospace; font-size: 11px; letter-spacing: 0.18em; text-transform: uppercase; color: #FF6E5B; }
  </style>`;

function renderIndexCard(post) {
  return `        <a href="/blog/${post.slug}/" class="blog-card">
          <div class="blog-card-meta">
            <span>${escText(post.category)}</span>
          </div>
          <h2 class="blog-card-title">${escText(post.title)}</h2>
          <p class="blog-card-excerpt">${escText(post.excerpt)}</p>
          <span class="blog-card-more">
            Read the post
            <svg width="11" height="8" viewBox="0 0 14 10" fill="none" aria-hidden="true"><path d="M1 5 H13 M9 1 L13 5 L9 9" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/></svg>
          </span>
        </a>`;
}

function renderIndex(posts) {
  const cards = posts.map(renderIndexCard).join('\n\n');
  return `<!doctype html>
<html lang="en">
<!-- GENERATED by scripts/build-blog.mjs — do not edit directly. -->
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="Writing from the Malibu team — network updates, engineering notes, and the ideas behind turning idle Apple Silicon into the world's largest AI cloud." />
  <link rel="canonical" href="${SITE}/blog/" />
  <meta property="og:title" content="Malibu · Blog" />
  <meta property="og:description" content="Writing from the Malibu team — network updates, engineering notes, and the ideas behind the network." />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="${SITE}/blog/" />
  <title>Malibu · Blog</title>
${HEAD_ASSETS}
${INDEX_STYLE}
</head>
<body>

<!-- ============ FLOATING NAV ============ -->
${nav('blog-nav-menu', true)}

<main id="top" style="background: #143A45; color: #FFFBF2; min-height: 100vh;">

  <!-- ============ HEADER ============ -->
  <section style="position: relative; padding: clamp(120px, 18vh, 200px) clamp(20px, 5vw, 80px) clamp(48px, 6vh, 72px);">
    <div aria-hidden="true" style="position: absolute; top: 0; left: 30%; right: 30%; height: 260px; background: radial-gradient(ellipse at top, rgba(255, 110, 91,0.18), transparent 70%); pointer-events: none;"></div>
    <div style="position: relative; max-width: 900px; margin: 0 auto;">
      <div style="font-family: 'JetBrains Mono', monospace; font-size: 10px; letter-spacing: 0.28em; text-transform: uppercase; color: #FFC629; margin-bottom: 18px;">The Malibu blog</div>
      <h1 style="font-family: 'Hanken Grotesk', sans-serif; font-weight: 500; font-size: clamp(56px, 8vw, 128px); line-height: 0.9; letter-spacing: -0.035em; color: #FFFBF2; margin: 0;">
        Writing <em style="font-style: normal; color: #FF6E5B;">from the network.</em>
      </h1>
      <p style="font-family: 'Hanken Grotesk', sans-serif; font-size: clamp(16px, 1.4vw, 20px); line-height: 1.5; color: rgba(255, 251, 242,0.72); margin: 22px 0 0; max-width: 60ch;">
        Network updates, engineering notes, and the ideas behind turning every idle Apple Silicon Mac into part of the world's biggest AI cloud.
      </p>
    </div>
  </section>

  <!-- ============ POSTS ============ -->
  <section style="position: relative; padding: 0 clamp(20px, 5vw, 80px) clamp(96px, 14vh, 160px);">
    <div style="position: relative; max-width: 900px; margin: 0 auto;">
      <div class="blog-list">

${cards}

      </div>
    </div>
  </section>

  <!-- ============ FOOTER ============ -->
${footer()}
</main>

<script type="module" src="/src/nav.js"></script>
</body>
</html>
`;
}

// ---------------------------------------------------------------------------
// sitemap.xml + feed.xml
// ---------------------------------------------------------------------------

function renderSitemap(posts) {
  const staticRoutes = ['/', '/blog/', '/network/', '/host/'];
  const urls = [
    ...staticRoutes.map((path) => `  <url>\n    <loc>${SITE}${path}</loc>\n  </url>`),
    ...posts.map(
      (p) =>
        `  <url>\n    <loc>${SITE}/blog/${p.slug}/</loc>\n    <lastmod>${p.date}</lastmod>\n  </url>`,
    ),
  ];
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.join('\n')}
</urlset>
`;
}

function renderFeed(posts) {
  const items = posts
    .map(
      (p) => `    <item>
      <title>${escText(p.title)}</title>
      <link>${p.canonical}</link>
      <guid isPermaLink="true">${p.canonical}</guid>
      <pubDate>${new Date(p.date).toUTCString()}</pubDate>
      <description>${escText(p.description || p.excerpt)}</description>
    </item>`,
    )
    .join('\n');
  const lastBuild = posts.length ? new Date(posts[0].date).toUTCString() : new Date(0).toUTCString();
  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Malibu · Blog</title>
    <link>${SITE}/blog/</link>
    <description>Network updates, engineering notes, and the ideas behind turning idle Apple Silicon into the world's biggest AI cloud.</description>
    <language>en-us</language>
    <lastBuildDate>${lastBuild}</lastBuildDate>
    <atom:link href="${SITE}/blog/feed.xml" rel="self" type="application/rss+xml" />
${items}
  </channel>
</rss>
`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  const posts = loadPosts();
  if (!posts.length) {
    console.warn('build-blog: no posts found in blog/posts/*.md');
  }

  for (const post of posts) {
    const dir = join(blogDir, post.slug);
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, 'index.html'), renderPost(post));
  }

  writeFileSync(join(blogDir, 'index.html'), renderIndex(posts));

  writeFileSync(join(publicDir, 'sitemap.xml'), renderSitemap(posts));
  mkdirSync(join(publicDir, 'blog'), { recursive: true });
  writeFileSync(join(publicDir, 'blog', 'feed.xml'), renderFeed(posts));

  console.log(
    `build-blog: ${posts.length} post(s) → blog/<slug>/index.html, blog/index.html, sitemap.xml, blog/feed.xml`,
  );
}

main();
